# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_ordered_numeric <- function(x) {
    .Call('_tibbletime3_is_ordered_numeric', PACKAGE = 'tibbletime3', x)
}

sorted_range_search <- function(x, lower, upper) {
    .Call('_tibbletime3_sorted_range_search', PACKAGE = 'tibbletime3', x, lower, upper)
}

